### ISSUE TITLE
Address changed

### ISSUE THREAD

**Issue by brainopia** [grosser/smusher#1]
New address is http://developer.yahoo.com/yslow/smushit and there is no currently available api 
(supposedly it will work as before but via ttp://developer.yahoo.com/yslow/smushit/ws.php)

excerpt from faq:
IS THERE A SMUSH.IT API I CAN ACCESS SO THAT MY IMAGES ARE AUTOMATICALLY SMUSHED WHEN THEY ARE PUBLISHED?

The API currently is not available for public use. We are working towards making this publicly accessible .

**Comment by grosser** [comment]
thanks, ill change it to use the new url

**Comment by grosser** [comment]
does not work so far, even the yslow page uses the old smush.it ws.php ...
