### ISSUE TITLE
smusher image test

### ISSUE THREAD

**Issue by dieuit07** [grosser/smusher#10]
Hi grosser , I test smusher images but image lost little less. Here is my test

smushing /home/wf04/Pictures/test/building.png               (7.1mb)
smush.it: No files were uploaded
7424136 -> 7424136                       = 100%

smushing /home/wf04/Pictures/test/checkmark.png  
17768 -> 17657                           = 99%                                  (17.2kb)

smushing /home/wf04/Pictures/test/hdtest.jpg                   (35.1kb)
35925 -> 35026                           = 97%                                 (34.2kb)

smushing /home/wf04/Pictures/test/pencil.jpg                   (22.3kb)
22796 -> 22462                           = 98%                                (21.9kb)

smushing /home/wf04/Pictures/test/home.jpg                    (22.4kb)
22910 -> 22144                           = 96%                                 (21.6kb)
And in my folder still have one image : mario.bmp           (2.3mb)        it not be smusher 

Did I do something wrong ??

**Comment by grosser** [comment]
Looks good to me, some images are already optimized and cannot be reduced further.
BMP is not supported.
