### ISSUE TITLE
Error while smushing images

### ISSUE THREAD

**Issue by anuseb** [grosser/smusher#2]
I have a folder named '10' and an image welcome_upgrade.jpg in it.
## When i smush it using smusher 10/ , i get the following error:

smushing 10/welcome_upgrade.jpg
618: unexpected token at '<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>301 Moved Permanently</title>
</head><body>

<h1>Moved Permanently</h1>

<p>The document has moved <a href="http://developer.yahoo.com/yslow/smushit/ws.php">here</a>.</p>

</body></html>
'
## 87211 -> 87211                           = 100%

Any help?

Thanks,
Anu

**Comment by grosser** [comment]
should be fixed, thanks for the report :)
