### ISSUE TITLE
Untitled

### ISSUE THREAD

**Issue by anuseb** [grosser/smusher#3]
I have a folder named '10' and an image welcome_upgrade.jpg in it.
## When i smush it using smusher 10/ , i get the following error:

smushing 10/welcome_upgrade.jpg
"618: unexpected token at '<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">"

'
## 87211 -> 87211                           = 100%

Any help?

Thanks,
Anu

**Comment by grosser** [comment]
i am trying to get it working again, but this seems not as simple as switching the url, they changed something and atm im debugging/trying to get it working

**Comment by anuseb** [comment]
Hi,
Thanks for your response.
Hope you would be able to fix this soon.
Thanks,
Anu

**Comment by grosser** [comment]
should be fixed
