### ISSUE TITLE
smush.it url

### ISSUE THREAD

**Issue by jacqueminv** [grosser/smusher#4]
The url used to call smush.it is incorrect at the moment.

Use instead the one from the ruby gem: http://ws1.adq.ac4.yahoo.com/ysmush.it/ws.php

By the way `smoosher.py` cannot be run in command line for 2 reasons:
1. no shebang at the top (if it is intended, please put in the doc)
2. `if __name__ == "__main__":` not included

**Comment by grosser** [comment]
smosher.py ?
i think you got the wrong project...

**Comment by jacqueminv** [comment]
Yes sorry please delete the issue
