### ISSUE TITLE
the gem version deleted a bunch of gifs... 

### ISSUE THREAD

**Issue by mmmurf** [grosser/smusher#5]
In the output it showed the gifs being converted to size 0 ... they no longer work after this occurred.

**Comment by grosser** [comment]
This should not happen, if anything is size 0 it should not be stored.
Can you send me one of these gifs so i can test them ?
(or better yet: can you add a testcase with them that fails)

**Comment by nicksergeant** [comment]
This happened to me, too:

smushing media/images/homepage-crossover.gif
2623 -> 0                                = 0%

Here's the image:

http://autoswatch.com/media/images/homepage-crossover.gif

**Comment by grosser** [comment]
im not able to reproduce this bug <-> i think its a communication problem

the gif was converted to a .png, ill try to make this visible in the output

**Comment by grosser** [comment]
0.4.7 should fix that, please reopen if its not fixed for you

**Comment by nicksergeant** [comment]
Thanks!
