### ISSUE TITLE
gem install smusher says : "undefined method `name' for #<RubyToken::TkLPAREN:0x7f689703f7f8>"

### ISSUE THREAD

**Issue by KnuX** [grosser/smusher#7]
Hi,

When trying to install smusher, I got this message :

$ sudo gem install smusher
Successfully installed httpclient-2.2.0.2
Successfully installed smusher-0.4.8
2 gems installed
Installing ri documentation for httpclient-2.2.0.2...

RDoc failure in lib/httpclient.rb at or around line 402 column 16

Before reporting this, could you check that the file
you're documenting compiles cleanly--RDoc is not a
full Ruby parser, and gets confused easily if fed
invalid programs.

The internal error was:

ERROR:  While executing gem ... (NoMethodError)
    undefined method `name' for #RubyToken::TkLPAREN:0x7f689703f7f8

My config :
- Ubuntu Lucid
  ii  ruby                                      4.2                                                An interpreter of object-oriented scripting 
  ii  ruby-dev                                  4.2                                                Header files for compiling extension modules
  ii  ruby1.8                                   1.8.7.249-2                                        Interpreter of object-oriented scripting lan
  ii  ruby1.8-dev                               1.8.7.249-2                                        Header files for compiling extension modules
  ii  rubygems                                  1.3.5-1ubuntu2                                     package management framework for Ruby librar
  ii  rubygems1.8                               1.3.5-1ubuntu2                                     package management framework for Ruby librar

**Comment by grosser** [comment]
smusher was installed anyway -> open this issue for httpclient instead, they need to fix their rdoc...
Id generally advise to not install ri / rdoc
`cat 'gem: --no-ri --no-rdoc' > ~/.gemrc`
