### ISSUE TITLE
Smusher can't find the server

### ISSUE THREAD

**Issue by jpcody** [grosser/smusher#8]
On all of my images for the past week or so, I've been getting the following:

getaddrinfo: nodename nor servname provided, or not known (http://ws1.adq.ac4.yahoo.com:80)

Perhaps it could be user error. If so, I'm not sure how.

**Comment by conatus** [comment]
The server is apparently not there any more. Trying to locate the new one is seemingly not an easy task.

**Comment by conatus** [comment]
http://www.smushit.com/ysmush.it/ws.php appears to be working okay, but can't test the uploads.

**Comment by grosser** [comment]
just swapping it in the config does not work ?

**Comment by grosser** [comment]
my fault, its hardcoded :D

**Comment by grosser** [comment]
found the new url :)

i also made the url overwriteable so its possible to hotfix it without updating.

--> 0.4.9
