### ISSUE TITLE
how can I using it with paperclip upload to s3

### ISSUE THREAD

**Issue by dieuit07** [grosser/smusher#9]
I try to place "smusher [url_image]" after Image.creat(params)< but it throw error : undefine method smusher 
Which way I can smusher image before paperclip upload it to s3 ???
Thank for your attention.

**Comment by the-architect** [comment]
Without knowing exactly if this works, I would do the following:

Cache the uploaded file locally on your server, then smush it using exec "smusher #{filename_of_upload}" (preferably in a background job using delayed job or resque) and then upload it to the desired S3 bucket.

**Comment by grosser** [comment]
Sounds like a good recommendation,
ideally you should not stop your current rails process for image processing.

Instead of exec use system or sh, or you current process will stop.

```
unless system("smusher #{filename_of_upload}")
  ... report image has failed ...
end
upload_image filename_of_upload # upload it anyway, either smushed or unsmushed
```

**Comment by dieuit07** [comment]
Thank you two ,the-architect and grosser :D

**Comment by dieuit07** [comment]
I try to do system("smusher /home/wf04/Pictures/test/checkmark.png")          It run fine on console

I alway give : /usr/bin/env: ruby: No such file or directory

And how to edit gem paperclip to upload to host heroku (run smusher) then upload to s3 

Please help me run this thing . Thank you so much :D

**Comment by grosser** [comment]
try `which smusher` and then use the absolute path in your script (and make sure smusher is installed...)
maybe even simpler try `bundle exec smusher`...

I have no idea about paperclip callbacks, ask the paperclip guys ;)

**Comment by dieuit07** [comment]
the error is gone but smusher still fail :D

**Comment by dieuit07** [comment]
`unless system("smusher #{filename_of_upload}")
  ... report image has failed ...
end`
this is alway false . I debug by debug1.9 , it smush fine +)

**Comment by grosser** [comment]
Works for me, can you retry with an image that is known to work, e.g. https://github.com/grosser/smusher/raw/master/spec/images/people.jpg

`
bundle exec smusher people.jpg && echo WORKS
smushing spec/images/people.jpg
2458 -> 2310                             = 93%
WORKS
`

**Comment by dieuit07** [comment]
picture test good, thank you :D
